from convokit.transformer import Transformer
from convokit.model import Corpus
from nltk.tokenize import word_tokenize


class PolTracker(Transformer):
    """
    Extracts information about invoking the self in utterances.

    """
    def __init__(self):
        self.ATTR_NAME = "politicization_reference_transformer"
        self.key_words = set(
            ["terms absentee ballot",
            "absolutism",
            "acquisitive model",
            "actual malice",
            "administrative adjudication",
            "affirm",
            "affirmative action",
            "agency capture",
            "agency representation",
            "agenda-setting",
            "amendment",
            "American conservatism",
            "American exceptionalism",
            "American liberalism",
            "Americans with Disabilities Act",
            "amicus curiae brief",
            "anarchism",
            "appellate jurisdiction",
            "appointment power",
            "appropriation",
            "Articles of Confederation",
            "attack journalism",
            "Australian ballot",
            "authoritarian regime",
            "authority",
            "authorization",
            "autocracy",
            "bad-tendency rule",
            "Bakke case",
            "balanced budget",
            "bicameral legislature",
            "bilateral",
            "bill",s
            "bill of attainder",
            "Bill of Rights",
            "Bipartisan Campaign Finance Reform Act",
            "bipolar system",
            "blanket primary",
            "block grant",
            "blog",
            "brief",
            "broadcast media",
            "Brown v. Board of Education of Topeka",
            "Kansas",
            "bundling",
            "bureaucracy",
            "buying power",
            "cabinet",
            "caesaropapism",
            "candidate-centered politics",
            "case law",
            "casework",
            "categorical grants",
            "caucus",
            "census",
            "central bank",
            "centralization",
            "centrally planned economy",
            "charter",
            "checks and balances",
            "chief of state",
            "citizen",
            "civic education",
            "civil liberties",
            "civil rights",
            "Civil Rights Act of 1964",
            "Civil Rights Cases",
            "civil service",
            "Civil Service Commission",
            "Civil Service Reform Act of 1883",
            "Civil Service Reform Act of 1978",
            "civil society",
            "civil war",
            "classical conservatism",
            "classical liberalism",
            "clear-and-present danger",
            "closed primary",
            "closed rule",
            "cloture",
            "codetermination",
            "command economy",
            "commerce clause",
            "common-carrier role",
            "common law",
            "communism",
            "comparative politics",
            "concurrent powers",
            "concurring opinion",
            "confederacy",
            "confederate system",
            "conformism",
            "constituency",
            "constitution",
            "constitutional democracy",
            "constitutional government",
            "constitutional powers",
            "continuing resolution",
            "conventional participation",
            "convention delegate",
            "cooperative federalism",
            "corrupt practices acts",
            "credentials committee",
            "critical election",
            "dealignment",
            "decision",
            "Declaration of Independence",
            "de facto segregation",
            "defamation of character",
            "deficit spending",
            "de jure segregation",
            "delegated powers",
            "demand-side economics",
            "democracy",
            "democratic socialism",
            "demosclerosis",
            "denial of power",
            "depression",
            "deregulation",
            "deterrence",
            "devolution",
            "dictatorship",
            "diplomacy",
            "direct democracy",
            "discharge petition",
            "dissenting opinion",
            "diversity",
            "divided government",
            "divine right theory of kingship",
            "division of labor",
            "dual federalism",
            "due process clause",
            "duopoly",
            "Earned Income Tax Credit",
            "economic aid",
            "economic group",
            "economic growth",
            "effective tax rate",
            "elastic clause",
            "elector",
            "Electoral College",
            "elitism/elite theory",
            "emergency powers",
            "empire",
            "enabling legislation",
            "entitlement program",
            "enumerated powers",
            "environmental impact statement",
            "environmentalism",
            "equality of opportunity",
            "equality of outcome",
            "equal protection clause",
            "Equal Rights Amendment",
            "equal time rule",
            "equity",
            "establishment clause",
            "excess demand",
            "exclusionary rule",
            "executive leadership",
            "Executive Office of the President",
            "executive order",
            "executive privilege",
            "ex post facto law",
            "expressed powers",
            "fairness doctrine",
            "faithless elector",
            "fascism",
            "federal budget",
            "Federal Communications Commission",
            "Federal Election Campaign Act",
            "Federal Election Commission",
            "federalism",
            "Federal Register",
            "federal reserve bank",
            "federal system",
            "feminism",
            "filibuster",
            "First Continental Congress",
            "fiscal federalism",
            "fiscal policy",
            "fiscal year",
            "527 groups",
            "flat taxes",
            "food stamps",
            "foreign policy",
            "formalized rules",
            "formula grants",
            "framers",
            "franking",
            "free exercise clause",
            "free rider",
            "front-loading",
            "front-runner",
            "full faith and credit clause",
            "fundamentalism",
            "gag order",
            "gender discrimination",
            "general election",
            "general jurisdiction",
            "gerrymandering",
            "Gibbons v. Ogden",
            "Gideon v. Wainwright",
            "globalization",
            "government",
            "Government Accountability Office",
            "government bond",
            "government corporation",
            "grandfather clause",
            "grant-in-aid",
            "grant of power",
            "grassroots activism",
            "Great Compromise",
            "gross domestic product",
            "guerrilla war",
            "gun control",
            "Hatch Act",
            "hierarchy",
            "home rule",
            "home style",
            "honeymoon period",
            "horizontal federalism",
            "hyperpluralism",
            "idealism",
            "ideology",
            "illegal participation",
            "impeachment",
            "implementation",
            "implied powers",
            "income distribution",
            "income transfer",
            "incorporation",
            "incrementalism",
            "independent",
            "independent executive agency",
            "independent regulatory agency",
            "individualism",
            "inflation",
            "informational benefits",
            "inherent powers",
            "in-kind subsidies",
            "inside game",
            "interest group",
            "international agreement",
            "internationalism",
            "international law",
            "international organization",
            "international system",
            "Internet media",
            "interpretive reporting",
            "intervention",
            "iron triangle",
            "isolationism",
            "issue advertising",
            "issue network",
            "Jim Crow laws",
            "Joint Chiefs of Staff",
            "judicial activism",
            "judicial implementation",
            "judicial philosophy",
            "judicial restraint",
            "judicial review",
            "jurisdiction",
            "justiciable question",
            "just-war theory",
            "Keynesian economics",
            "kitchen cabinet",
            "Kyoto Protocol",
            "laissez-faire capitalism",
            "lawmaking",
            "layer-cake federalism",
            "legislative agenda",
            "legitimacy",
            "Lemon test",
            "libel",
            "liberalism",
            "libertarianism",
            "liberty",
            "limited government",
            "limited jurisdiction",
            "limited war",
            "line-item veto",
            "line organization",
            "literacy test",
            "lobbying",
            "logrolling",
            "loophole",
            "loose constructionism",
            "machine",
            "Madisonian Model",
            "majority leader",
            "majority opinion",
            "majority party",
            "majority rule",
            "malapportionment",
            "mandate",
            "mandatory retirement",
            "marble-cake federalism",
            "markup",
            "material incentive",
            "McCain-Feingold bill",
            "McCulloch v. Maryland",
            "means-testing",
            "media",
            "media consolidation",
            "merit system",
            "Merit System Protection Board",
            "midterm election",
            "military aid",
            "military-industrial complex",
            "minority leader",
            "minority party",
            "Miranda v. Arizona",
            "mixed economy",
            "monarchy",
            "monetary policy",
            "monopolistic model",
            "Monroe Doctrine",
            "multiculturalism",
            "multilateralism",
            "multinational corporation",
            "multiple-member district",
            "multipolar system",
            "nation",
            "national convention",
            "national debt",
            "national interest",
            "nationalism",
            "National Security Council",
            "nation-building",
            "nation-state",
            "Nazism",
            "necessary and proper clause",
            "necessary evil",
            "negotiated rule-making",
            "neoconservatism",
            "New Deal coalition",
            "new federalism",
            "New Jersey Plan",
            "nihilism",
            "Nineteenth Amendment",
            "No Child Left Behind Act",
            "noneconomic group",
            "nongovernmental actor",
            "nongovernmental organization",
            "Nuclear Non-Proliferation Treaty",
            "objective reporting",
            "office-block ballot",
            "Office of Personnel Management",
            "oligarchy",
            "ombudsperson",
            "open primary",
            "open rule",
            "opinion",
            "opinion leader",
            "original intent",
            "original jurisdiction",
            "outside game",
            "overregulation",
            "oversight",
            "pack journalism",
            "paradox of participation",
            "pardon",
            "parliamentary democracy",
            "partisan journalism",
            "party activist",
            "party-centered politics",
            "party-column ballot",
            "party identification",
            "party in government",
            "party in the electorate",
            "party organization",
            "party platform",
            "party reform",
            "patronage",
            "Pendleton Act",
            "per curiam",
            "pigeonholing",
            "Plessy v. Ferguson",
            "pluralism",
            "plurality",
            "plurality opinion",
            "pocket veto",
            "political action committee",
            "political appointees",
            "political culture",
            "political economy",
            "political efficacy",
            "political equality",
            "political participation",
            "political party",
            "political science",
            "political socialization",
            "politics",
            "polling",
            "pollster",
            "poll tax",
            "popular sovereignty",
            "Populists",
            "pork",
            "poverty line",
            "power",
            "power of the purse",
            "precedent",
            "preemption",
            "Presidential Commission",
            "presidential democracy",
            "president pro tempore",
            "primary election",
            "print media",
            "prior restraint",
            "private bill",
            "private good",
            "privatization",
            "privileges and immunities clause",
            "probability sample",
            "professional legislature",
            "progressive taxes",
            "prohibited powers",
            "project grants",
            "proportional representation",
            "prospective voting",
            "proxy war",
            "public administration",
            "public assistance",
            "public education",
            "public good",
            "public opinion",
            "public policy",
            "public representative role",
            "purposive incentive",
            "rally ’round the flag effect",
            "random selection",
            "ranking member",
            "ratings game",
            "rational choice theory",
            "rationalism",
            "realignment",
            "realism",
            "reapportionment",
            "recession",
            "redistributive policy",
            "redistricting",
            "regime",
            "regressive taxes",
            "regulated federalism",
            "regulatory policy",
            "remand",
            "rent voucher",
            "representative democracy",
            "representative sample",
            "reprieve",
            "republic",
            "reregulation",
            "reserved powers",
            "responsible party",
            "retention election",
            "retrospective voting",
            "revenue agency",
            "revenue sharing",
            "reverse",
            "reverse discrimination",
            "revolution",
            "rider",
            "right of rebuttal",
            "rights of the minority",
            "Roe v. Wade",
            "rogue state",
            "roll-call vote",
            "rugged individualism",
            "rule-making",
            "rule of four",
            "sample",
            "sampling error",
            "school vouchers",
            "Second Continental Congress",
            "selective incentives",
            "selective incorporation",
            "self-selected candidate",
            "senatorial courtesy",
            "separation of powers",
            "sexual harassment",
            "Shays’ Rebellion",
            "signing message",
            "single-member district",
            "skewed sample",
            "slander",
            "social capital",
            "socialism",
            "social security",
            "sociological representation",
            "soft money",
            "solicitor general",
            "solidarity incentive",
            "sovereignty",
            "Speaker of the House",
            "special district",
            "special election",
            "specialization",
            "splinter party",
            "split-ticket voting",
            "spoiler",
            "spoils system",
            "staffer",
            "standard operating procedure",
            "stare decisis",
            "state",
            "statecraft",
            "State of the Union address",
            "statute",
            "stewardship theory",
            "straight-ticket voting",
            "strict constructionism",
            "subnationalism",
            "suffrage",
            "sunset provisions",
            "sunshine laws",
            "superdelegate",
            "Super Tuesday",
            "Supplemental Security Income",
            "supply-side economics",
            "supremacy clause",
            "supremacy doctrine",
            "surplus",
            "symbolic speech",
            "system of government",
            "talk radio",
            "tax credit",
            "Temporary Assistance to Need Families",
            "term limits",
            "terrorism",
            "third party",
            "Three-Fifths Compromise",
            "totalitarian government",
            "total war",
            "transnational",
            "trickle-down economics",
            "trustee representation",
            "tyranny of the majority",
            "unconventional participation",
            "underemployment",
            "unemployment",
            "unfunded mandate",
            "unilateral",
            "unipolar",
            "unitary system",
            "unity",
            "user fee",
            "veto",
            "veto message",
            "Virginia Plan",
            "voter turnout",
            "voting behavior",
            "Voting Rights Act",
            "War Powers Resolution",
            "Washington community",
            "watchdog journalism",
            "Weberian model",
            "welfare",
            "welfare state",
            "whip",
            "whistleblower",
            "White House staff",
            "white primary",
            "winner take all",
            "writ of certiorari",
            "writ of habeas corpus",
            "yellow journalism",
            "Michael Bennet",
            "Joe Biden",
            "Cory Booker",
            "Steve Bullock",
            "Pete Buttigieg",
            "Julian Castro",
            "John Delaney",
            "Tulsi Gabbard",
            "Kamala Harris",
            "Amy Kobluchar",
            "Wayne Messam",
            "Beto O’Rourke",
            "Donald Trump",
            "Mark Sanford",
            "Bill Weld",
            "Joe Walsh",
            "Hillary Clinton",
            "Gary Johnson",
            "Jill Stein",])

        ##code goes here

    def transform(self, corpus: Corpus):
        """Adds metadata about self-reflection to each utterance.

        :param corpus: the corpus to compute features for.
        :type corpus: Corpus
        """
        
        #for conv_id in corpus.conversations:
        #    conv = corpus.get_conversation(conv_id)
        #    for utt in conv.iter_utterances():
        #        if utt.text != None:
        #            tokenized = word_tokenize(utt.text.lower())
        #            invocations = 0
        #            for token in tokenized:
        #                if token in self.key_words:
        #                    invocations += 1
        #            utt.meta["num_self_invocations"] = invocations
        return corpus